galaxy_info:
  author: Frank Muise
  description: Helper role providing tasks and playbooks for Technitium DNS integration tests
  license: GPL-3.0-or-later
  min_ansible_version: 2.12
  platforms: []
dependencies: []
