---
cluster_dns_servers_to_create:
  - name: "cluster_primary01{{ container_suffix }}"
    http_port: "{{ api_port_cluster_primary_01 }}"
    https_port: "{{ https_port_cluster_primary_01 }}"
    dns_server_domain: "cluster-primary01.local"
    image_tag: "latest"
  - name: "cluster_secondary01{{ container_suffix }}"
    http_port: "{{ api_port_cluster_secondary_01 }}"
    https_port: "{{ https_port_cluster_secondary_01 }}"
    dns_server_domain: "cluster-secondary01.local"
    image_tag: "latest"
  - name: "cluster_secondary02{{ container_suffix }}"
    http_port: "{{ api_port_cluster_secondary_02 }}"
    https_port: "{{ https_port_cluster_secondary_02 }}"
    dns_server_domain: "cluster-secondary02.local"
    image_tag: "latest"

# Login Info
admin_username: admin
admin_password: topsecret

safe_job_id: thisisverysafe
container_suffix: .example.com