---
# Wrapper playbook

- name: Local playbook for setting up testing environments
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../../../tests/integration/integration_config.yml"
    - "{{ playbook_dir }}/../../../tests/integration/targets/setup_testing_env/vars/config.yml"
  tasks:
    - name: Setup testing environment
      include_tasks: "{{ playbook_dir }}/../../../tests/integration/targets/setup_testing_env/tasks/main.yml"
